### ISSUE TITLE
How to get backup of EdgeSwitch in rancid

### ISSUE THREAD

**Issue by PuranRai** [shouptech/rancidscripts#1]
Hello everyone,
      I have installed rancid and viewvc. And i am success for getting backup of Cisco devices. But its time to get the EdgeSwitch backup. I am not getting it. Please help!!!
![edgeswitch rancid](https://user-images.githubusercontent.com/44667253/47908541-84027300-deb5-11e8-95d4-7e6bde4658d9.JPG)

**Comment by shouptech** [comment]
Unfortunately, I do not have an EdgeSwitch for to test this script with. It is written for the EdgeRouter, and is largely unmaintained.

Good luck.

**Comment by PuranRai** [comment]
Thanks Mike Shoup, 
Is there any one who have me for this problem. Please help.
